name: Gradle CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up Rust
      uses: actions-rs/cargo@v1.0.3
    - name: Grant execute permission for install_compiler_x86_64.sh
      run: chmod +x ./setup/install_compiler_x86_64.sh
    - name: Set up BuildTools
      run: sudo ./setup/install_compiler_x86_64.sh
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: ReleaseBuild with Gradle
      run: ./gradlew release --info
    - name: Test with Gradle
      run: ./gradlew test --info
